---
title: "Estadísticas de Uruguay"
description: |
  Estadísticas de Uruguay
author:
  - name: Manuel Spínola
    url: http://www.icomvis.una.ac.cr/index.php/manuel
    affiliation: ICOMVIS - UNA
    affiliation_url: http://www.icomvis.una.ac.cr/
    orcid: 0000-0002-7839-1908
date: 04-08-2022
citation: true
draft: true
categories:
  - "Estadísticas de Uruguay"
---

```{r}
#| message: false
#| warning: false
#| include: false
library(tidyverse)
library(rio)
library(tibble)
library(ech)
library(geouy)
library(ggthemes)
library(archive)
```

```{r}
#| eval: false
df <- get_microdata(year = 2017, folder = "datos", toR = TRUE)
```

```{r}
df_H_2011 <- import("datos/ech_2011_sav/H_2011_TERCEROS.sav")
df_HyP_2011 <- import("datos/ech_2011_sav/FUSIONADO_2011_TERCEROS.sav")
df_P_2011 <- import("datos/ech_2011_sav/P_2011_TERCEROS.sav")
```

```{r}
df_H_2012 <- import("datos/ech_2012_sav/H_2012_TERCEROS.sav")
df_HyP_2012 <- import("datos/ech_2012_sav/FUSIONADO_2012_TERCEROS.sav")
df_P_2012 <- import("datos/ech_2012_sav/P_2012_TERCEROS.sav")
```

```{r}
df_H_2013 <- import("datos/ech_2013_sav/H_2013_TERCEROS.sav")
df_HyP_2013 <- import("datos/ech_2013_sav/FUSIONADO_2013_TERCEROS.sav")
df_P_2013 <- import("datos/ech_2013_sav/P_2013_TERCEROS.sav")
```

```{r}
df_H_2014 <- import("datos/ech_2014_sav/H_2014_Terceros.sav")
df_HyP_2014 <- import("datos/ech_2014_sav/Fusionado_2014_Terceros.sav")
df_P_2014 <- import("datos/ech_2014_sav/P_2014_Terceros.sav")
```

```{r}
df_H_2015 <- import("datos/ech_2015_sav/H_2015_Terceros.sav")
df_HyP_2015 <- import("datos/ech_2015_sav/HyP_2015_Terceros.sav")
df_P_2015 <- import("datos/ech_2015_sav/P_2015_Terceros.sav")
```

```{r}
df_H_2016 <- import("datos/ech_2016_sav/H_2016_Terceros.sav")
df_HyP_2016 <- import("datos/ech_2016_sav/HyP_2016_Terceros.sav")
df_P_2016 <- import("datos/ech_2016_sav/P_2016_Terceros.sav")
```

```{r}
df_H_2017 <- import("datos/ech_2017_sav/H_2017_Terceros.sav")
df_HyP_2017 <- import("datos/ech_2017_sav/HyP_2017_Terceros.sav")
df_P_2017 <- import("datos/ech_2017_sav/P_2017_Terceros.sav")
```

```{r}
df_H_2018 <- import("datos/ech_2018_sav/H_2018_Terceros.sav")
df_HyP_2018 <- import("datos/ech_2018_sav/HyP_2018_Terceros.sav")
df_P_2018 <- import("datos/ech_2018_sav/P_2018_Terceros.sav")
```

```{r}
df_H_2019 <- import("datos/ech_2019_sav/H_2019_Terceros.sav")
df_HyP_2019 <- import("datos/ech_2019_sav/HyP_2019_Terceros.sav")
df_P_2019 <- import("datos/ech_2019_sav/P_2019_Terceros.sav")
```

# 2020

```{r}
df_HyP_2020 <- import("datos/ech_2020_sav/SAV/HyP_2020_Terceros.sav")
```

```{r}
df_HyP_2021 <- import("datos/ech_2021.csv")
```

```{r}
df_HyP_2011 <- poverty(df_HyP_2011, ht11 = "HT11", ht19 = "HT19")
df_HyP_2011 <- enrolled_school(df_HyP_2011)
df_HyP_2011 <- years_of_schooling(df_HyP_2011)
df_HyP_2011 <- unsatisfied_basic_needs(df_HyP_2011)
df_HyP_2011 <- integrated_poverty_measure(df_HyP_2011)
```

```{r}
df_HyP_2012 <- poverty(df_HyP_2012)
df_HyP_2012 <- enrolled_school(df_HyP_2012)
df_HyP_2012 <- years_of_schooling(df_HyP_2012)
df_HyP_2012 <- unsatisfied_basic_needs(df_HyP_2012)
df_HyP_2012 <- integrated_poverty_measure(df_HyP_2012)
```

```{r}
df_HyP_2013 <- poverty(df_HyP_2013)
df_HyP_2013 <- enrolled_school(df_HyP_2013)
df_HyP_2013 <- years_of_schooling(df_HyP_2013)
df_HyP_2013 <- unsatisfied_basic_needs(df_HyP_2013)
df_HyP_2013 <- integrated_poverty_measure(df_HyP_2013)
```

```{r}
df_HyP_2014 <- poverty(df_HyP_2014)
df_HyP_2014 <- enrolled_school(df_HyP_2014)
df_HyP_2014 <- years_of_schooling(df_HyP_2014)
df_HyP_2014 <- unsatisfied_basic_needs(df_HyP_2014)
df_HyP_2014 <- integrated_poverty_measure(df_HyP_2014)
```

```{r}
df_HyP_2015 <- poverty(df_HyP_2015)
df_HyP_2015 <- enrolled_school(df_HyP_2015)
df_HyP_2015 <- years_of_schooling(df_HyP_2015)
df_HyP_2015 <- unsatisfied_basic_needs(df_HyP_2015)
df_HyP_2015 <- integrated_poverty_measure(df_HyP_2015)
```

```{r}
df_HyP_2016 <- poverty(df_HyP_2016)
df_HyP_2016 <- enrolled_school(df_HyP_2016)
df_HyP_2016 <- years_of_schooling(df_HyP_2016)
df_HyP_2016 <- unsatisfied_basic_needs(df_HyP_2016)
df_HyP_2016 <- integrated_poverty_measure(df_HyP_2016)
```

```{r}
df_HyP_2017 <- poverty(df_HyP_2017)
df_HyP_2017 <- enrolled_school(df_HyP_2017)
df_HyP_2017 <- years_of_schooling(df_HyP_2017)
df_HyP_2017 <- unsatisfied_basic_needs(df_HyP_2017)
df_HyP_2017 <- integrated_poverty_measure(df_HyP_2017)
```

```{r}
df_HyP_2018 <- poverty(df_HyP_2018)
df_HyP_2018 <- enrolled_school(df_HyP_2018)
df_HyP_2018 <- years_of_schooling(df_HyP_2018)
df_HyP_2018 <- unsatisfied_basic_needs(df_HyP_2018)
df_HyP_2018 <- integrated_poverty_measure(df_HyP_2018)
```

```{r}
names(df_HyP_2019)
```

```{r}
df_HyP_2019 <- organize_names(df_HyP_2019, year = 2019, level = "hyp")
```

```{r}
df_HyP_2019 <- poverty(df_HyP_2019, ht11 = "HT11")
df_HyP_2019 <- enrolled_school(df_HyP_2019)
df_HyP_2019 <- years_of_schooling(df_HyP_2019)
df_HyP_2019 <- unsatisfied_basic_needs(df_HyP_2019)
df_HyP_2019 <- integrated_poverty_measure(df_HyP_2019)
```

```{r}
df_HyP_2020 <- poverty(df_HyP_2020)
df_HyP_2020 <- enrolled_school(df_HyP_2020)
df_HyP_2020 <- years_of_schooling(df_HyP_2020)
df_HyP_2020 <- unsatisfied_basic_needs(df_HyP_2020)
df_HyP_2020 <- integrated_poverty_measure(df_HyP_2020)
```

```{r}
df_HyP_2021 <- poverty(df_HyP_2021)
df_HyP_2021 <- enrolled_school(df_HyP_2021)
df_HyP_2021 <- years_of_schooling(df_HyP_2021)
df_HyP_2021 <- unsatisfied_basic_needs(df_HyP_2021)
df_HyP_2021 <- integrated_poverty_measure(df_HyP_2021)
```

# 2015

```{r}
# Distribución de hogares según cantidad de NBI que presenta
nbi_hogares_2015 <- get_estimation_mean(df_HyP_2015, variable = "UBN", level = "h")

# Distribución de personas según cantidad de NBI que presenta el hogar
nbi_personas_2015 <- get_estimation_mean(df_HyP_2015, variable = "UBN", level = "i")

# Hogares según situación de pobreza 
pobres_hogares_2015 <- get_estimation_mean(df_HyP_2015, variable = "poor", level = "h")

# Personas según situación de pobreza 
pobres_personas_2015 <- get_estimation_mean(df_HyP_2015, variable = "poor", level = "i")

# Hogares según situación de pobreza
ipm_hogares_2015 <- get_estimation_mean(df_HyP_2015, variable = "integrated_poverty_measure", level = "h")
```

# 2016

```{r}
# Distribución de hogares según cantidad de NBI que presenta
nbi_hogares_2016 <- get_estimation_mean(df_HyP_2016, variable = "UBN", level = "h")

# Distribución de personas según cantidad de NBI que presenta el hogar
nbi_personas_2016 <- get_estimation_mean(df_HyP_2016, variable = "UBN", level = "i")

# Hogares según situación de pobreza 
pobres_hogares_2016 <- get_estimation_mean(df_HyP_2016, variable = "poor", level = "h")

# Personas según situación de pobreza 
pobres_personas_2016 <- get_estimation_mean(df_HyP_2016, variable = "poor", level = "i")

# Hogares según situación de pobreza
ipm_hogares_2016 <- get_estimation_mean(df_HyP_2016, variable = "integrated_poverty_measure", level = "h")
```

# 2017

```{r}
# Distribución de hogares según cantidad de NBI que presenta
nbi_hogares_2017 <- get_estimation_mean(df_HyP_2017, variable = "UBN", level = "h")

# Distribución de personas según cantidad de NBI que presenta el hogar
nbi_personas_2017 <- get_estimation_mean(df_HyP_2017, variable = "UBN", level = "i")

# Hogares según situación de pobreza 
pobres_hogares_2017 <- get_estimation_mean(df_HyP_2017, variable = "poor", level = "h")

# Personas según situación de pobreza 
pobres_personas_2017 <- get_estimation_mean(df_HyP_2017, variable = "poor", level = "i")

# Hogares según situación de pobreza
ipm_hogares_2017 <- get_estimation_mean(df_HyP_2017, variable = "integrated_poverty_measure", level = "h")
```

# 2018

```{r}
# Distribución de hogares según cantidad de NBI que presenta
nbi_hogares_2018 <- get_estimation_mean(df_HyP_2018, variable = "UBN", level = "h")

# Distribución de personas según cantidad de NBI que presenta el hogar
nbi_personas_2018 <- get_estimation_mean(df_HyP_2018, variable = "UBN", level = "i")

# Hogares según situación de pobreza 
pobres_hogares_2018 <- get_estimation_mean(df_HyP_2018, variable = "poor", level = "h")

# Personas según situación de pobreza 
pobres_personas_2018 <- get_estimation_mean(df_HyP_2018, variable = "poor", level = "i")

# Hogares según situación de pobreza
ipm_hogares_2018 <- get_estimation_mean(df_HyP_2018, variable = "integrated_poverty_measure", level = "h")
```

# 2019

```{r}
df_HyP_2019$poor
```

```{r}
# Distribución de hogares según cantidad de NBI que presenta
nbi_hogares_2019 <- get_estimation_mean(df_HyP_2019, variable = "UBN", level = "h")

# Distribución de personas según cantidad de NBI que presenta el hogar
nbi_personas_2019 <- get_estimation_mean(df_HyP_2019, variable = "UBN", level = "i")

# Hogares según situación de pobreza 
pobres_hogares_2019 <- get_estimation_mean(df_HyP_2019, variable = "poor", level = "h")

# Personas según situación de pobreza 
pobres_personas_2019 <- get_estimation_mean(df_HyP_2019, variable = "poor", level = "i")

# Hogares según situación de pobreza
ipm_hogares_2019 <- get_estimation_mean(df_HyP_2019, variable = "integrated_poverty_measure", level = "h")
```

```{r}
ipm_hogares_2015
```

```{r}
pobres_personas_2015$año <- c(2015, 2015)
pobres_personas_2016$año <- c(2016, 2016)
pobres_personas_2017$año <- c(2017, 2017)
pobres_personas_2018$año <- c(2018, 2018)
pobres_personas_2019$año <- c(2019, 2019)
```

```{r}
pobres_all <- bind_rows(pobres_personas_2015, pobres_personas_2016, pobres_personas_2017, pobres_personas_2018)
```

```{r}
pobres_all
```

```{r}
ggplot(pobres_all, aes(año, estimacion, group = poor, color = poor)) +
  geom_line(position = position_dodge(width = 0.9)) +
  geom_point(position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = estimacion_low, ymax = estimacion_upp), width = 0.15, position = position_dodge(width = 0.9))
```

```{r}
ipm_hogares_2015$año <- c(2015, 2015, 2015, 2015)
ipm_hogares_2016$año <- c(2016, 2016, 2016, 2016)
ipm_hogares_2017$año <- c(2017, 2017, 2017, 2017)
ipm_hogares_2018$año <- c(2018, 2018, 2018, 2018)
ipm_hogares_2019$año <- c(2019, 2019, 2019, 2019)
```

```{r}
ipm_all <- bind_rows(ipm_hogares_2015, ipm_hogares_2016, ipm_hogares_2017, ipm_hogares_2018, ipm_hogares_2019)
```

```{r}
ggplot(ipm_all, aes(año, estimacion, group = integrated_poverty_measure, color = integrated_poverty_measure)) +
  theme_minimal(base_size = 12) +
  geom_line(position = position_dodge(width = 0.9)) +
  geom_point(position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = estimacion_low, ymax = estimacion_upp), width = 0.15, position = position_dodge(width = 0.9)) +
  geom_label(aes(label = round(estimacion, 2)), position = position_dodge(width = 0.9), size = 3, label.padding = unit(0.05, "lines"), show.legend  = FALSE) +
  labs(x = "Año",
       y = "Valor de pobreza integrada",
       caption = "Fuente: Encuesta Continua de Hogares") +
  scale_color_tableau(name = "Pobreza")
```

```{r}
con <- archive_extract("datos/ech_2011_sav.rar")
list.files(con)
```

```{r}
uy <- load_geouy("Uruguay")
```

```{r}
ggplot(uy) +
  geom_sf()
```

```{r}
df <- get_microdata(year = 2019)
```

```{r}
pobre_x_dpto <- as.data.frame(cbind(nomdpto = c("ARTIGAS", "DURAZNO", "FLORIDA", "LAVALLEJA"),
               Pobreza = c(0.26, 0.27, 0.07, 0.10)))
pobre_x_dpto_geo <- add_geom(data = pobre_x_dpto, unit = "Departamentos", variable = "nomdpto")
```

```{r}
ggplot(pobre_x_dpto_geo) +
  geom_sf(aes(fill = Pobreza))
```

```{r}
pobre_x_dpto_geo
```

```{r}
depor <- geouy::load_geouy("Instituciones deportivas")
```

```{r}
ggplot(depor) +
  geom_sf(data = uy) +
  geom_sf()
```

```{r}
df <- get_microdata(year = 2019)
df <- organize_names(df, year = 2019)
```
