---
title: "Untitled"
editor: source
---

```{r}
#| message: false
#| warning: false
library(tidyverse)
library(rio)
library(sf)
library(stars)
library(raster)
library(rasterVis)
library(terra)
library(tidyterra)
library(rnaturalearth)
library(rmapshaper)
library(exactextractr)
library(landscapemetrics)
library(landscapetools)
library(motif)
library(supercells)
library(ggdark)
library(arcpullr)
library(basemaps)
library(rayshader)
library(elevatr)
library(here)
```

```{r}
sa <- ne_countries(continent = "south america", scale = 10, returnclass = "sf")
```

```{r}
uy <- sa |> dplyr::filter(iso_a3 == "URY")
```

```{r}
uy <- ms_filter_islands(uy, min_area = 1000000000)
```

```{r}
uy_pseudo <- st_transform(uy, crs = 3857)
```

```{r}
uy_dem <- get_elev_raster(uy, z = 10, clip = "locations")
```

```{r}
uy_dem <- rast(uy_dem)
```

```{r}
uy_dem_pseudo <- terra::project(uy_dem, "EPSG:3857")
```

```{r}
uy_dem_pseudo <- raster(uy_dem_pseudo)
```


```{r}
plot(uy_dem_pseudo)
```


```{r}
writeRaster(uy_dem_pseudo, file = here("posts/2022-10-18-uruguay-mapas/rasters/uy_dem_pseudo.tif"), overwrite = TRUE)
```

```{r}
g <- basemap_geotif(uy, map_service = "esri", map_type = "world_imagery")
```

```{r}
gr <- rast(g)
```

```{r}
gr
```

```{r}
plot(gr)
```

```{r}
uy_satelite <- mask(gr, uy_pseudo)
```

```{r}
plotRGB(uy_satelite)
```

```{r}
names(uy_satelite) = c("r","g","b")
```

```{r}
uy_satelite <- raster::stack(uy_satelite)
```

```{r}
writeRaster(uy_satelite, file = "/Users/manuelspinola/Documents/01-Manolo/R_ciencia_datos_blog_quarto/posts/2022-10-18-uruguay-mapas/rasters/uy_satelite.tif", overwrite = TRUE)
```

```{r}
uy_dem_m <- rayshader::raster_to_matrix(uy_dem_pseudo)
```

```{r}
uy_sat_m_r <- rayshader::raster_to_matrix(uy_satelite$r)
uy_sat_m_g <- rayshader::raster_to_matrix(uy_satelite$g)
uy_sat_m_b <- rayshader::raster_to_matrix(uy_satelite$b)
```

```{r}
uy_sat_m = rayshader::raster_to_matrix(uy_satelite)
```

```{r}
uy_sat_m_array = array(0,dim=c(nrow(uy_satelite),ncol(uy_satelite),3))
```

```{r}
uy_sat_m_array[,,1] = uy_sat_m_r/170 #Red layer
uy_sat_m_array[,,2] = uy_sat_m_g/170 #Blue layer
uy_sat_m_array[,,3] = uy_sat_m_b/170 #Green layer
```

```{r}
uy_sat_m_array = aperm(uy_sat_m_array, c(2,1,3))
```

```{r}
plot_map(uy_sat_m_array)
```

```{r}
uy_rgb_contrast = scales::rescale(uy_sat_m_array,to=c(0,1))
```

```{r}
plot_map(uy_rgb_contrast)
```

```{r}
plot_3d(uy_rgb_contrast,
        uy_dem_m,
        windowsize = c(1100,900),
        zscale = 15,
        shadowdepth = -50,
        zoom=0.5,
        phi=45,
        theta=-45,
        fov=70,
        background = "white",
        shadowcolor = "gray")
```


```{r}
render_snapshot(here("plot_3d/cr_satelite_3d_b.png")
```

```{r}
render_highquality(filename = here("plot_3d/cr_satelite_3d.png"),
	lightintensity=1500,
	lightaltitude=90)
```


```{r}
plot_3d(cr_rgb_contrast,
        cr_dem_m,
        windowsize = c(1200,1000), 
        solid = FALSE, 
        zscale = 10,
        phi = 45, 
        zoom = 0.5, 
        theta = -45,
        shadowdepth = -100)
```

```{r}
render_highquality(filename = here("plot_3d/cr_satelite_3d.png"),
	lightintensity=1500,
	lightaltitude=90)
```
